/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.feedbackinterfaces2.vista;

import com.mycompany.feedbackinterfaces2.controlador.Funciones;
import com.mycompany.feedbackinterfaces2.modelo.conexion.ConexionMySql;
import com.mysql.jdbc.Connection;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class JFIncidencias extends javax.swing.JFrame {

    /**
     * Creates new form JFIncidencias
     */
    public JFIncidencias() {
        initComponents();
        cargarComboboxClientes();
        cargarComboboxSecciones();
        cargarComboboxEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCSeccion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rSDateDesde = new rojeru_san.componentes.RSDateChooser();
        jLabel6 = new javax.swing.JLabel();
        rSDateHasta = new rojeru_san.componentes.RSDateChooser();
        jBBuscar = new javax.swing.JButton();
        jBInsertar = new javax.swing.JButton();
        jBModi = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jButtonPdf = new javax.swing.JButton();
        jButtonExcel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIncidencias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INCIDENCIAS");

        jLabel2.setText("Cliente");

        jCCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Sección");

        jCSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Estado");

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEstadoActionPerformed(evt);
            }
        });

        jLabel5.setText("F. desde");

        jLabel6.setText("F. hasta");

        jBBuscar.setText("BUSCAR");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBInsertar.setText("INSERTAR");

        jBModi.setText("MODIFICAR");

        jBEliminar.setText("ELIMINAR");

        jButtonPdf.setText("Informe PDF");
        jButtonPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPdfActionPerformed(evt);
            }
        });

        jButtonExcel.setText("Informe EXCEL");
        jButtonExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcelActionPerformed(evt);
            }
        });

        jTableIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Id.", "Descripción", "Sección", "Fecha", "Importe", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableIncidencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCSeccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(rSDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(rSDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonPdf)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonExcel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBInsertar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBModi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6)
                    .addComponent(rSDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jBBuscar)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBModi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEliminar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPdf)
                    .addComponent(jButtonExcel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        mostrarIncidencias();

    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jButtonPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPdfActionPerformed
        //http://www.laurafolgado.es/desarrollointerfaces/2017/02/incluir-informes-jasper-en-un-proyecto-de-java-swing/
        try {

            //los parametros a 0 
            Map<String, Object> parameters = new HashMap();
            parameters.put("cliente", txtCliente);
            parameters.put("seccion", txtSeccion);
            parameters.put("estado", txtEstado);
            parameters.put("fechaDesde", txtFechaDesde);
            parameters.put("fechaHasta", txtFechaHasta);
            //1.Obtenemos la conexión

            //2.Obtenemos el objeto JasperPrint
            JasperPrint jasperPrint
                    = JasperFillManager.fillReport("./src/main/java/com/mycompany/feedbackinterfaces2/vista/reports/incidencias.jasper", parameters, c);
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            //3.Realizamos la exportación a formato pdf
            //   JasperExportManager
            //  .exportReportToPdfFile(jasperPrint, "./src/main/java/com/mycompany/feedbackinterfaces2/reports/incidencias.pdf");
            //   File path = new File ("./src/main/java/com/mycompany/feedbackinterfaces2/reports/incidencias.pdf");
            //  Desktop.getDesktop().open(path);

            viewer.setVisible(true);
            viewer.setTitle("Informe Incidencias");

        } catch (JRException ex) {
            Logger.getLogger(JFIncidencias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPdfActionPerformed

    private void jButtonExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcelActionPerformed
        try {
            //1.Obtenemos la conexión
            ConexionMySql con = new ConexionMySql();
            Connection c = con.conectar();

            //2.Obtenemos el objeto JasperPrint
            JasperPrint jasperPrint
                    = JasperFillManager.fillReport("./src/main/java/com/mycompany/feedbackinterfaces2/reports/incidencias.jasper", null, c);

            //3.Realizamos la exportación a formato html
            JasperExportManager
                    .exportReportToHtmlFile(jasperPrint, "./src/main/java/com/mycompany/feedbackinterfaces2/reports/incidencias.html");

            File path = new File("./src/main/java/com/mycompany/feedbackinterfaces2/reports/incidencias.html");
            Desktop.getDesktop().open(path);

        } catch (JRException ex) {
            Logger.getLogger(JFIncidencias.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFIncidencias.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonExcelActionPerformed

    private void jCEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFIncidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFIncidencias().setVisible(true);
            }
        });
    }

    /**
     * Cargamos la lista desplegable de clientes con los datos que hay en la
     * BBDD en la tabla clientes.
     *
     * @param clientes
     */
    public void cargarComboboxClientes() {
        try {
            ConexionMySql con = new ConexionMySql();
            Connection c = con.conectar();
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("select concat(nombre,'  ',apellidos) as nombre from clientes");
            jCCliente.removeAllItems();
            jCCliente.addItem("**Todos**");
            while (rs.next()) {
                jCCliente.addItem(rs.getString(1));

            }
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFIncidencias.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     *
     */
    public void cargarComboboxSecciones() {
        try {
            ConexionMySql con = new ConexionMySql();
            Connection c = con.conectar();
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("select  nombre  from secciones");
            jCSeccion.removeAllItems();
            jCSeccion.addItem("**Todos**");
            while (rs.next()) {
                jCSeccion.addItem(rs.getString(1));

            }
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFIncidencias.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void cargarComboboxEstado() {
        try {
            ConexionMySql con = new ConexionMySql();
            Connection c = con.conectar();
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("select concat(codigo,'  ',descripcion) as estado from estado");
            jCEstado.removeAllItems();
            jCEstado.addItem("**Todos**");
            while (rs.next()) {
                jCEstado.addItem(rs.getString(1));

            }
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFIncidencias.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Método que rellena la jTble, una vez que se pulsa el botón BUSCAR.
     */
    public void mostrarIncidencias() {

        DefaultTableModel modelo = new DefaultTableModel();

        try {
            txtCliente = Funciones.devolverIdCliente(jCCliente.getSelectedItem().toString());
            txtSeccion = Funciones.devolverIdSeccion(jCSeccion.getSelectedItem().toString());
            txtEstado = Funciones.devolverIdEstado(jCEstado.getSelectedItem().toString());
            if (rSDateDesde.getDatoFecha() != null) {
                txtFechaDesde = Funciones.convert(rSDateDesde.getDatoFecha());
            }
            if (rSDateHasta.getDatoFecha() != null) {
                txtFechaHasta = Funciones.convert(rSDateHasta.getDatoFecha());
            }

            ResultSet datos = Funciones.consultarIncidencias(txtCliente, txtSeccion, txtEstado, txtFechaDesde, txtFechaHasta);

            ResultSetMetaData rsMd = datos.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();
            modelo.addColumn("Cliente");
            modelo.addColumn("Id");
            modelo.addColumn("Descripción");
            modelo.addColumn("Sección");
            modelo.addColumn("Fecha");
            modelo.addColumn("Importe");
            modelo.addColumn("Estado");

            while (datos.next()) {
                Object[] filas = new Object[numeroColumnas];
                for (int i = 0; i < numeroColumnas; i++) {
                    filas[i] = datos.getObject(i + 1);

                }

                modelo.addRow(filas);

            }
            jTableIncidencias.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }

    //Valores recogidos en las listas desplegables
    Integer txtCliente = 0;
    Integer txtSeccion = 0;
    Integer txtEstado = 0;
    java.sql.Date txtFechaDesde = null;
    java.sql.Date txtFechaHasta = null;
   
    
    //Conexion
    ConexionMySql con = new ConexionMySql();
    Connection c = con.conectar();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBInsertar;
    private javax.swing.JButton jBModi;
    private javax.swing.JButton jButtonExcel;
    private javax.swing.JButton jButtonPdf;
    private javax.swing.JComboBox<String> jCCliente;
    private javax.swing.JComboBox<String> jCEstado;
    private javax.swing.JComboBox<String> jCSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIncidencias;
    private rojeru_san.componentes.RSDateChooser rSDateDesde;
    private rojeru_san.componentes.RSDateChooser rSDateHasta;
    // End of variables declaration//GEN-END:variables
}
